apiVersion: apps/v1
kind: Deployment
metadata:
  name: johntechdep
spec:
  selector:
    matchLabels:
      app: johntechapp
  template:
    metadata:
      labels:
        app: johntechapp
    spec:
      containers:
      - name: johntechcont
        image: henry5/johntech-webapp:1
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 8080
