apiVersion: apps/v1
kind: Deployment
metadata:
  name: johntechdep
spec:
  selector:
    matchLabels:
      app: johntechapp
  template:
    metadata:
      labels:
        app: johntechapp
    spec:
      containers:
      - name: johntechcont
        image: henry5/johntech-webapp:1
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: joetechsvc
  labels:
    app: johntechsvc
spec:
  type: LoadBalancer
  selector:
    app: johntechapp
  ports:
  - port: 80
    targetPort: 8080        
